$directories = @(
    "docs/vision",
    "docs/architecture",
    "docs/runtime",
    "docs/planner",
    "docs/agents",
    "docs/provider",
    "docs/workflow",
    "docs/memory",
    "docs/plugins",
    "docs/sdk",
    "docs/ui",
    "docs/examples",
    "docs/adr",
    "docs/rfcs",
    "specs/domain",
    "specs/api",
    "specs/events",
    "specs/interfaces",
    "specs/schemas",
    "design/diagrams",
    "design/sequence",
    "design/state-machine",
    "design/flow",
    "design/ui",
    "templates/project",
    "templates/backend",
    "templates/frontend",
    "templates/microservice",
    "templates/helm",
    "templates/docker",
    "templates/github",
    "examples",
    "sdk",
    "orchestrator",
    "runtime/scheduler",
    "runtime/executor",
    "runtime/queue",
    "runtime/events",
    "runtime/session",
    "runtime/context",
    "runtime/logging",
    "runtime/metrics",
    "planner",
    "providers",
    "tools/git",
    "tools/terminal",
    "tools/docker",
    "tools/kubernetes",
    "tools/browser/playwright",
    "tools/browser/puppeteer",
    "tools/browser/selenium",
    "tools/browser/chrome_driver",
    "tools/filesystem",
    "tools/ssh",
    "tools/jira",
    "tools/figma",
    "tools/database",
    "tools/http_client",
    "tools/code_search",
    "tools/github",
    "tools/aws",
    "tools/gcp",
    "tools/slack",
    "tools/security",
    "tools/profiler",
    "tools/backend/go",
    "tools/backend/python",
    "tools/backend/node",
    "tools/backend/docker_sandbox",
    "tools/backend/compiler",
    "tools/backend/runner",
    "internal",
    "scripts",
    "tests",
    "playground"
)

foreach ($dir in $directories) {
    if (Test-Path $dir) {
        $gitkeep = "$dir/.gitkeep"
        if (-not (Test-Path $gitkeep)) {
            New-Item -ItemType File -Force -Path $gitkeep | Out-Null
        }
        # Set file attribute to Hidden in Windows
        $file = Get-Item -Path $gitkeep -Force
        $file.Attributes = 'Hidden'
    }
}
Write-Host "Restored and hid .gitkeep files!"
