// Package provider defines the contract for AI provider integrations.
package provider

import "encoding/json"

// =============================================================================
// Message Roles
// =============================================================================

// Role represents the role of a message sender in a conversation.
type Role string

const (
	// RoleSystem defines AI behavior.
	RoleSystem Role = "system"

	// RoleUser represents messages from human users or the orchestrator.
	RoleUser Role = "user"

	// RoleAssistant represents responses generated by the AI model.
	RoleAssistant Role = "assistant"

	// RoleTool contains tool execution output feedbacks.
	RoleTool Role = "tool"
)

// IsValid checks if the role matches any defined constant.
func (r Role) IsValid() bool {
	switch r {
	case RoleSystem, RoleUser, RoleAssistant, RoleTool:
		return true
	default:
		return false
	}
}

// String returns the string representation of the role.
func (r Role) String() string {
	return string(r)
}

// =============================================================================
// Message
// =============================================================================

// Message represents a single message in a conversation.
type Message struct {
	Role       Role       `json:"role"`
	Content    string     `json:"content"`
	ToolCalls  []ToolCall `json:"tool_calls,omitempty"`
	ToolCallID string     `json:"tool_call_id,omitempty"`
	Name       string     `json:"name,omitempty"`
}

// =============================================================================
// Tool Call
// =============================================================================

// ToolCall represents the AI's request to execute a tool/function.
type ToolCall struct {
	ID   string          `json:"id"`
	Name string          `json:"name"`
	Args json.RawMessage `json:"arguments"`
}

// =============================================================================
// Helper Functions
// =============================================================================

// NewSystemMessage creates a system message.
func NewSystemMessage(content string) Message {
	return Message{Role: RoleSystem, Content: content}
}

// NewUserMessage creates a user message.
func NewUserMessage(content string) Message {
	return Message{Role: RoleUser, Content: content}
}

// NewAssistantMessage creates an assistant message with text content.
func NewAssistantMessage(content string) Message {
	return Message{Role: RoleAssistant, Content: content}
}

// NewToolResultMessage creates a tool result message.
func NewToolResultMessage(toolCallID string, content string) Message {
	return Message{
		Role:       RoleTool,
		Content:    content,
		ToolCallID: toolCallID,
	}
}

// HasToolCalls returns true if this is an assistant message with tool calls.
func (m *Message) HasToolCalls() bool {
	return m.Role == RoleAssistant && len(m.ToolCalls) > 0
}
